name: proteome
version: 0.3.17.0
synopsis: neovim project manager
description: Please see the README on GitHub at <https://github.com/tek/proteome-hs>
github: "tek/proteome-hs"
license: MIT
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2018 Torsten Schmits"
category: Neovim
build-type: Simple

extra-source-files:
- README.md

dependencies:
- MissingH
- aeson
- ansi-terminal
- base >= 4.7 && < 5
- bytestring
- composition-extra
- containers
- data-default-class
- deepseq
- directory
- either
- extra
- filepath
- filepattern
- hslogger
- lens
- messagepack
- mtl
- nvim-hs
- pretty-terminal
- prettyprinter
- process
- resourcet
- ribosome
- safe
- split
- stm
- text
- time
- transformers
- unliftio
- utf8-string

library:
  source-dirs: lib

executables:
  proteome:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proteome

tests:
  proteome-unit:
    main: SpecMain.hs
    source-dirs: test/u
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proteome
    - HTF

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UnicodeSyntax
- ViewPatterns
