resolver: lts-9.1
packages:
- .
extra-deps:
  - nvim-hs-1.0.0.3
  - prettyprinter-1.2.1
  - cereal-conduit-0.8.0
  - conduit-1.3.0
  - resourcet-1.2.2
  - unliftio-0.2.8.0
  - unliftio-core-0.1.1.0
  - mono-traversable-1.0.9.0
  - time-1.7.0.1
  - strings-1.1
