resolver: lts-12.26
packages:
- .
# - ../ribosome/modules/core
# - ../ribosome/modules/test
extra-deps:
- base-noprelude-4.11.1.0
- strings-1.1
- pretty-terminal-0.1.0.0
- posix-pty-0.2.1.1
- filepattern-0.1.1
- fuzzy-0.1.0.0
- github: neovimhaskell/nvim-hs
  commit: 8b1a38c18f530f65a17a7fda2a14c168a2663821
- github: tek/cornea
  commit: fe735cb878e43ea2a257346f4f228cd04fa77b4c
- github: tek/chiasma
  commit: a15987575a5da2606d4cea110a8e8d7aa9ce8446
- github: tek/ribosome
  commit: 6c7a4bd7f2fc0d8ca7b1a0c5e96b99a5240cd48a
  subdirs:
  - modules/core
  - modules/test
