version: 0.3.17.0
description: Please see the README on GitHub at <https://github.com/tek/proteome>
github: tek/proteome
license: BSD-2-Clause-Patent
license-file: LICENSE
author: Torsten Schmits
maintainer: tek@tryp.io
copyright: 2021 Torsten Schmits
category: Neovim
build-type: Simple
